// Package models defines the data structures used throughout the RSS worker.
//
// The models map directly to Supabase/PostgreSQL tables and are serialized
// as JSON for the REST API. Key models include:
//   - Source: RSS feed configuration
//   - Article: Parsed article with deduplication via URL hash
//   - FetchLog: Monitoring record for each fetch run
//   - FetchResult: Per-source fetch statistics
package models

import (
	"crypto/sha256"
	"encoding/hex"
	"time"
)

// Source represents an RSS feed source from the database
type Source struct {
	ID                 string     `json:"id"`
	Name               string     `json:"name"`
	Slug               string     `json:"slug"`
	FeedURL            string     `json:"feed_url"`
	WebsiteURL         *string    `json:"website_url"`
	LogoURL            *string    `json:"logo_url"`
	CategoryID         *string    `json:"category_id"`
	Language           string     `json:"language"`
	IsActive           bool       `json:"is_active"`
	LastFetched        *time.Time `json:"last_fetched_at"`
	FetchIntervalHours int        `json:"fetch_interval_hours"`
	// Embedded category info from PostgREST ?select=*,categories(name,slug)
	Categories *EmbeddedCategory `json:"categories,omitempty"`
}

// EmbeddedCategory holds category name/slug from PostgREST embedding.
type EmbeddedCategory struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CategoryName returns the category name from embedded category data.
func (s *Source) CategoryName() string {
	if s.Categories != nil {
		return s.Categories.Name
	}
	return ""
}

// CategorySlug returns the category slug from embedded category data.
func (s *Source) CategorySlug() string {
	if s.Categories != nil {
		return s.Categories.Slug
	}
	return ""
}

// ShouldFetch returns true if the source is due for fetching based on its interval.
func (s *Source) ShouldFetch() bool {
	if s.LastFetched == nil {
		return true
	}
	interval := s.FetchIntervalHours
	if interval <= 0 {
		interval = 2 // default 2 hours
	}
	return time.Since(*s.LastFetched) >= time.Duration(interval)*time.Hour
}

// Article represents a news article to be stored in the database.
// Articles are deduplicated by URLHash (SHA256 of URL) to prevent duplicates
// when the same article appears in multiple RSS fetches.
// Supports text articles, podcasts (audio), and videos via media fields.
type Article struct {
	ID            string    `json:"id,omitempty"`                  // UUID, auto-generated by database
	Title         string    `json:"title"`                         // Article headline
	Summary       *string   `json:"summary"`                       // Short description, typically from RSS
	Content       *string   `json:"content"`                       // Full article text, extracted via go-readability
	URL           string    `json:"url"`                           // Original article URL
	URLHash       string    `json:"url_hash"`                      // SHA256(URL) for deduplication
	ImageURL      *string   `json:"image_url"`                     // High-res image, preferring og:image
	ThumbnailURL  *string   `json:"thumbnail_url"`                 // Original RSS thumbnail (often low-res)
	Author        *string   `json:"author"`                        // Article author name
	SourceID      string    `json:"source_id"`                     // FK to sources table
	CategoryID    *string   `json:"category_id"`                   // FK to categories table (inherited from source)
	Language      string    `json:"language"`                      // ISO 639-1 language code (inherited from source)
	PublishedAt   time.Time `json:"published_at"`                  // Original publication timestamp
	MediaType     *string   `json:"media_type,omitempty"`          // "podcast" or "video", nil for articles
	MediaURL      *string   `json:"media_url,omitempty"`           // Direct URL to audio/video file
	MediaDuration *int      `json:"media_duration,omitempty"`      // Duration in seconds
	MediaMIMEType *string   `json:"media_mime_type,omitempty"`     // MIME type (audio/mpeg, video/mp4, etc.)
	SourceName    *string   `json:"source_name,omitempty"`         // Denormalized source name
	SourceSlug    *string   `json:"source_slug,omitempty"`         // Denormalized source slug
	CategoryName  *string   `json:"category_name,omitempty"`       // Denormalized category name
	CategorySlug  *string   `json:"category_slug,omitempty"`       // Denormalized category slug
}

// NewArticle creates a new Article with computed URL hash
func NewArticle(title, url, sourceID string, categoryID *string, language string, publishedAt time.Time) *Article {
	return &Article{
		Title:       title,
		URL:         url,
		URLHash:     HashURL(url),
		SourceID:    sourceID,
		CategoryID:  categoryID,
		Language:    language,
		PublishedAt: publishedAt,
	}
}

// HashURL generates a SHA256 hash of the URL for deduplication
func HashURL(url string) string {
	hash := sha256.Sum256([]byte(url))
	return hex.EncodeToString(hash[:])
}

// Category represents a news category
type Category struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	DisplayOrder int    `json:"display_order"`
}

// FetchLog tracks the status of a fetch operation
type FetchLog struct {
	ID                string     `json:"id,omitempty"`
	StartedAt         time.Time  `json:"started_at"`
	CompletedAt       *time.Time `json:"completed_at"`
	SourcesProcessed  int        `json:"sources_processed"`
	ArticlesFetched   int        `json:"articles_fetched"`
	ArticlesInserted  int        `json:"articles_inserted"`
	ArticlesSkipped   int        `json:"articles_skipped"`
	Errors            []string   `json:"errors"`
	Status            string     `json:"status"` // running, completed, failed
}

// FetchResult holds the result of fetching a single source
type FetchResult struct {
	Source          Source
	ArticlesFetched int
	ArticlesInserted int
	ArticlesSkipped  int
	Error           error
}
